// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN7lgLWwHHRaTlOT1rNGL0rGYVhy6J...',
    appId: '1:285237934364:web:5a94203aca05aa33dc6...',
    messagingSenderId: '285237934...',
    projectId: 'thebestlocaleats-b6***',
    authDomain: 'thebestlocaleats-b6***.firebaseapp.com',
    storageBucket: 'thebestlocaleats-b6***.appspot.com',
    measurementId: 'G-3R6YH42...',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8bMKeCR864zyCQmm4kB8ERsKDTfDG...',
    appId: '1:285237934364:android:2d0f1957adb0f626dc6...',
    messagingSenderId: '285237934...',
    projectId: 'thebestlocaleats-b6***',
    storageBucket: 'thebestlocaleats-b6***.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARWB0aDx1FrtZPbUz7i0qu2owIBsWY...',
    appId: '1:285237934364:ios:d0cb1b8c0ad3bbbcdc6...',
    messagingSenderId: '285237934...',
    projectId: 'thebestlocaleats-b6***',
    storageBucket: 'thebestlocaleats-b6***.appspot.com',
    androidClientId: '285237934364-7e7tgfrvhtnoer0htbor2b4r9s0li***.apps.googleusercontent.com',
    iosClientId: '285237934364-60pnuoojuhvm2nl6f6odmg0qgknf6***.apps.googleusercontent.com',
    iosBundleId: 'com.example.kalamazoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARWB0aDx1FrtZPbUz7i0qu2owIBsWY...',
    appId: '1:285237934364:ios:d0cb1b8c0ad3bbbcdc6...',
    messagingSenderId: '285237934...',
    projectId: 'thebestlocaleats-b6***',
    storageBucket: 'thebestlocaleats-b6***.appspot.com',
    androidClientId: '285237934364-7e7tgfrvhtnoer0htbor2b4r9s0li***.apps.googleusercontent.com',
    iosClientId: '285237934364-60pnuoojuhvm2nl6f6odmg0qgknf6***.apps.googleusercontent.com',
    iosBundleId: 'com.example.kalamazoo',
  );
}
